import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Banner from "~/components/banner";

import PageComponent from "~/components/pagecomponent";
import { StateDemo } from "~/components/stateDemo";
import { ZustandDemo } from "~/components/zustandDemo";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const fancyapi = api.somefancy.morelayers.useMutation();

  const [userinput, userinput_set] = useState("");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Banner />
      </main>
    </>
  );
};

export default Home;
